/**
 * Type extensions for Macrodata
 *
 * Base Env is generated by `wrangler types` from wrangler.jsonc + .dev.vars
 * We augment Cloudflare.Env with runtime-injected bindings.
 */

import type { OAuthHelpers } from "@cloudflare/workers-oauth-provider";

declare global {
  namespace Cloudflare {
    interface Env {
      OAUTH_PROVIDER: OAuthHelpers;
    }
  }
}

export {};
